#%RAML 1.0 NamedExample
add-cust-portfolio-example:
  customer_id: 1
  portfolio_name: "gift"
  stock_symbol: "AMZN"
  quantity: 1
  buy_price: 30
  sell_price: 20
  status: buy
  buy_date: 2022-10-12
  sell_date: 2022-10-16