#%RAML 1.0 NamedExample
cust-docExample:
  customer_id: 1
  doc_type: "pancard"
  image_url: "https://loremflickr.com/cache/resized/5612_15642033907_f46d73bcb6_320_240_nofilter.jpg"
  doc_status: "verfiy"