#%RAML 1.0 NamedExample
customerExample:
  id: 1
  first_name: "Manish"
  last_name: "Kumar"
  email: "manish.kumar@bitsinglass.com"
  phone: "7986726321"
  date_of_birth: "1993-12-12"
  gender: male
  employee_type: business
  annual_income: "10000"
  active: active