#%RAML 1.0
title: stock-sapi-api

protocols: [HTTP,HTTPS]
types:
  wallet: !include DataTypes/cust-walletDataType.raml
  updateCustomerWallet: !include DataTypes/update-cust-walletDataType.raml
  customer: !include DataTypes/customerDataType.raml
  updateCustomer: !include DataTypes/updateCustomerDataType.raml
  customer-document: !include DataTypes/cust-docDataType.raml
  cust-portfolio: !include DataTypes/cust-portfolio-dataType.raml
  add-cust-portfolio: !include DataTypes/add-cust-portfolio-dataType.raml
  
  
traits:
  errorResponses: !include traits/errorTrait.raml

securitySchemes:
  customSecurity: !include common/securityScheme.raml
securedBy:
  - customSecurity

/customer:
  post:
    is: [errorResponses]
    description: Add new customer.
    body:
      application/json:
        type: customer
        examples: !include Examples/customerExample.raml
    responses:
      201:
        body:
          application/json:
            example:
              {
                'success': true,
                'statusCode': 201,
                'message': 'The Customer ID 1 has been successfully created.'
              }
  
  /{customerId}:
    put:
      is: [errorResponses]
      description: Update customer detail
      body:
        application/json:
          type: updateCustomer
          examples: !include Examples/customerExample.raml
      responses:
        200:
          body:
            application/json:
              example:
                {
                'success': true,
                'statusCode': 200,
                'message': 'The Customer ID 1 has been successfully updated.'
              }
                
  

    get:
      is: [errorResponses]
      description: Get customer data by ID
      responses:
        200:
          body:
            application/json:
              type: customer
              examples: !include Examples/customerExample.raml
                

  /all:
    get:
      is: [errorResponses]
      description: Get all customer data
      queryParameters:
        limit:
          type: integer
          required: true
      responses:
        200:
          body:
            application/json:
              type: customer[]
              examples: !include Examples/customersExample.raml  


/customer-document:
  post:
    is: [errorResponses]
    description: Add the Customer Document details
    body:
      application/json:
        type: customer-document
        examples: !include Examples/cust-docExample.raml
    responses:
      201:
        body:
          application/json:
            example:
              {
                'success': true,
                'statusCode': 201,
                'message': 'The Customer Document has been successfully added.'
              }
  
  /{customerID}:
    get:
      is: [errorResponses]
      description: Get customer document by Id
      responses:
        200:
          body:
            application/json:
              type: customer-document
              examples: !include Examples/cust-docExample.raml

/customer-buy-stock/{stock-symbol}/{customer_id}:
  get:
    is: [errorResponses]
    description: Get details of customer portfolio
    responses:
      200:
        body:
          application/json:
            type: cust-portfolio
            examples: !include Examples/cust-portfolio-example.raml

/wallet:
  post:
    is: [errorResponses]
    description: Add the Customer wallet
    body:
      application/json:
        type: wallet
        examples: !include Examples/cust-walletExample.raml
    responses:
      201:
        body:
          application/json:
            example:
              {
                'success': true,
                'statusCode': 201,
                'message': 'The Customer wallet has been added successfully.'
              }
              

/getCustomerWalletAmount/{customer_id}:
  get:
    description: View customer wallet amount
    responses:
          200:
            body:
              application/json:
                examples: !include Examples/cust-wallet-amount.raml

/customerPortfolio/{customer_id}:
  post:
    is: [errorResponses]
    description: Add the data in customer portfolio
    body:
      application/json:
        type: add-cust-portfolio
        examples: !include Examples/add-cust-portfolio-example.raml
    responses:
      201:
        body:
          application/json:
            example:
              {
                'success': true,
                'statusCode': 201,
                'message': 'The stock has been added successfully in customer portfolio.'
              }

/getStockBySymbol/{symbol_name}:
  get:
    description: Get stock data by symbol name
    responses:
      200:
        body:
          application/json:
            examples: !include Examples/stock-data-example.raml





